### ISSUE TITLE
Invalid resource ID

### ISSUE THREAD

**Issue by victorfernandesraton** [google-pay/wallet-web-codelab#11]
When i try ussing `issuerId` variable as a `invitio` i got this error
```js
{message: 'Invalid resource ID: ISSUER_ID.codelab_class',domain: 'walletobjects',reason: 'invalidResource'}
```

**Comment by stephenmcd** [comment]
Hi, you haven't followed the steps in the codelab, specifically the line on page 4 that says "Replace the value of issuerId with your Issuer ID from the Google Pay & Wallet Console".

**Comment by Jurajzovinec** [comment]
@Viper-ui I am currently experiencing the same issue, have you found the problem :)?

**Comment by Viper-ui** [comment]
> @Viper-ui I am currently experiencing the same issue, have you found the problem :)?

@Jurajzovinec We have to use the issuer id that is in our google pay and wallet console but you need to have google issuer account for that to use the issuer id and to generate passes.
