### ISSUE TITLE
Create a real pass

### ISSUE THREAD

**Issue by suoko** [google-pay/wallet-web-codelab#4]
This code works for generic passes which are not an option when you create a real pass from google wallet api.
Did anyone find the code and json to test a real gift card or other passes?

**Comment by chrishenschel** [comment]
If I understand you correctly you want to redesign your card? I just called the current implemented json with this function:

```
const classId = '1234567-xxx-xxxx-xxxxxxxxx; // that one you got from the test account
async function getGenericClass(req, res) {
  const credentials = require(serviceAccountFile);

  const httpClient = new GoogleAuth({
    credentials: credentials,
    scopes: 'https://www.googleapis.com/auth/wallet_object.issuer'
  });

  
  objectResponse = await httpClient.request({ url: "https://walletobjects.googleapis.com/walletobjects/v1/genericClass/" + issuerId +'.'+ classId, method: 'GET'});

  console.log(objectResponse.data)
  res.send( objectResponse.data );
}
//...
app.get('/googlegetclass', getGenericClass);
//....
```
now you can edit the original pass and suit it to whatever you want. 
after that, you have to change the classId const in your code to whatever suits you. like "my-first-pass" and run this function to upload your layout. keep in mind that for new passes you should also use your classId.

```
const classId = 'my-new-class-id';
async function createGenericClass(req, res) {
  const credentials = require(serviceAccountFile);

  const httpClient = new GoogleAuth({
    credentials: credentials,
    scopes: 'https://www.googleapis.com/auth/wallet_object.issuer'
  });

  const objectPayload = require('./google_generic-pass_class.json');
  objectPayload.id = `${issuerId}.${classId}`;
  objectResponse = await httpClient.request({ url: "https://walletobjects.googleapis.com/walletobjects/v1/genericClass/", method: 'POST', data: objectPayload});

  console.log(objectResponse)
  res.send( objectResponse );
}
// .....
app.get('/googlecreatclass', createGenericClass);
// ....
```

**Comment by jtuttas** [comment]
I've wrote a small application to manager generic google wallet classes. Take a look at [here](https://github.com/jtuttas/googlegenericwalletmanager). The program can also run as a docker container, if you have docker installed simply type..

```
docker run -it -p 3000:3000 tuttas/googlewalletclassmanager
```

**Comment by ncalteen** [comment]
Hello,

It looks like this issue hasn't been updated in a while. If you're looking for sample code to create Google Wallet passes of different types, please refer to the [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples) repository. There you will find examples for creating pass classes and objects of multiple different types and in different programming languages.

I hope this helps! If you run into any trouble please open an issue in that repo and we will help out.

**Comment by gredajustyna** [comment]
Hello, I am struggling to design my own pass so I have a few more questions on this topic. I am running the codelab with a generic pass and everything works fine. How should I modify the code to include the functions mentioned above? The code doesn't work if I exclude the `app.post('/', createPassAndToken);` part. I also often get a `Default value for LocalizedString cannot be empty` error. Sorry if it's some basic knowledge, I'd be really glad if you could help me.

**Comment by chrishenschel** [comment]
> Hello, I am struggling to design my own pass so I have a few more questions on this topic. I am running the codelab with a generic pass and everything works fine. How should I modify the code to include the functions mentioned above? The code doesn't work if I exclude the `app.post('/', createPassAndToken);` part. I also often get a `Default value for LocalizedString cannot be empty` error. Sorry if it's some basic knowledge, I'd be really glad if you could help me.

Sadly I can't help you with those error messages. The two functions above show how you can download the sample pass (function: getGenericClass). if you store the output of that function to "./google_generic-pass_class.json" then you are able to use the second function (createGenericClass)  to upload this json as a new pass. So inside this json you can make modifications on how the pass should look like. Both are additional to the sample code.

**Comment by gredajustyna** [comment]
Thank you for the fast reply. Should the additional functions be called before or after `app.post('/', createPassAndToken);` ?

**Comment by chrishenschel** [comment]
Before to create your used pass. It is more like two utility functions which should not be exposed to "users" and are just for creating everything around.
