### ISSUE TITLE
Google codelabs wrong snippet

### ISSUE THREAD

**Issue by BPouw** [google-pay/wallet-web-codelab#5]
Hi,

Could not update this in the repo but if you follow the steps correctly in google codelabs it will ask you to paste the following snippet.

res.send(`<a href="${saveUrl}"><img src="button.png"></a>`);

for the wallet image to load correctly it should be

res.send(`<a href="${saveUrl}"><img src="wallet-button.png"></a>`);

**Comment by stephenmcd** [comment]
This is fixed now, thank you
