### ISSUE TITLE
Possible small mistake in tutorial

### ISSUE THREAD

**Issue by DevonTomatoSandwich** [google-pay/wallet-web-codelab#9]
For step 4 "Create a Generic pass class", at the bottom of the page it says 
"In this case, the suffix is set to codelab_class" 
When I cloned the repo the sufix is "test-class-id" i.e. my classId is defined as
```const classId = `${issuerId}.test-class-id\`;```
makes no difference anyway, I still completed the tutorial but just lettin ya know :)

**Comment by stephenmcd** [comment]
Thanks Jack, that's definitely a mistake, I fixed it in 07ceb9042055c278612cd9ee4e55c3bc417fce2a
